using Project.AuthSystem.API.src.Models;
using Project.AuthSystem.API.src.Models.Dtos;

namespace Project.AuthSystem.API.src.Services.Interfaces;
public interface IUserService
{
    /// <summary>
    /// Get a user informations
    /// </summary>
    /// <param name="identity">Identity generated by DB</param>
    Task<User> GetUser (Guid identity);

    /// <summary>
    /// Create a new user in Database
    /// </summary>
    /// <param name="user">User informations in JSON formatted</param>
    Task<User> NewUser(UserDto user);

    /// <summary>
    /// Update user informations in DB
    /// </summary>
    /// <param name="user">User informations</param>
    /// <param name="identity">Identitty generated by DB</param>
    Task<User> UpdateUser (UserDto user, Guid identity);

    /// <summary>
    /// Delete user from DB
    /// </summary>
    /// <param name="identity">Identity generated by DB</param>
    Task DeleteUser(Guid identity);

    /// <summary>
    /// Update user's password
    /// </summary>
    /// <param name="identity">Indetity generated by DB</param>
    Task<bool> UpdatePassword(Guid identity, string newPass);
}